'use client'

import { useState } from 'react'
import { Link } from 'wouter'
import { buttonVariants } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { 
  ArrowLeft, 
  HelpCircle, 
  Search, 
  Truck, 
  CreditCard, 
  RefreshCw, 
  ShieldCheck, 
  ChevronDown, 
  ChevronUp, 
  Mail 
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface FAQItem {
  id: string
  question: string
  points: string[]
  category: 'shipping' | 'payments' | 'returns' | 'security'
}

export default function FAQPage() {
  const [searchQuery, setSearchQuery] = useState('')
  const [activeCategory, setActiveCategory] = useState<'all' | 'shipping' | 'payments' | 'returns' | 'security'>('all')
  const [expandedItems, setExpandedItems] = useState<Record<string, boolean>>({
    'ship-1': true, // Keep the first one expanded by default
  })

  const categories = [
    { id: 'all', label: 'All FAQs', icon: HelpCircle },
    { id: 'shipping', label: 'Shipping & Delivery', icon: Truck },
    { id: 'payments', label: 'Orders & Payments', icon: CreditCard },
    { id: 'returns', label: 'Returns & Exchanges', icon: RefreshCw },
    { id: 'security', label: 'Account & Security', icon: ShieldCheck },
  ] as const

  const faqs: FAQItem[] = [
    {
      id: 'ship-1',
      category: 'shipping',
      question: "How long will it take to receive my order?",
      points: [
        "Order Processing: All orders are packed and dispatched within 1 to 2 business days.",
        "Standard Shipping: Takes 3 to 5 business days for domestic deliveries (Free on orders over $150).",
        "Express Delivery: Takes 1 to 2 business days (Available at checkout for a flat rate of $15.00).",
        "Tracking Link: Sent directly to your email as soon as the carrier registers and scans the parcel."
      ]
    },
    {
      id: 'ship-2',
      category: 'shipping',
      question: "Do you offer international shipping?",
      points: [
        "Supported Regions: We currently ship to the United States, Canada, Europe, and Australia.",
        "Duties & Taxes: Any customs duties or import taxes are automatically calculated at checkout.",
        "Delivery Timeline: International shipments generally arrive in 7 to 14 business days.",
        "Carrier Partners: We partner with DHL Express and FedEx International to ensure safe delivery."
      ]
    },
    {
      id: 'pay-1',
      category: 'payments',
      question: "Which payment methods do you accept?",
      points: [
        "Credit/Debit Cards: Visa, MasterCard, American Express, Discover, and JCB.",
        "Mobile Wallets: Apple Pay and Google Pay are supported for accelerated checkout.",
        "Stripe Gateway: All transactions are processed securely via Stripe's encrypted payment gateway.",
        "Zero Raw Data: We never store your raw credit card numbers or CVV codes on our servers."
      ]
    },
    {
      id: 'pay-2',
      category: 'payments',
      question: "Can I cancel or modify my order after placing it?",
      points: [
        "Cancellation Window: You can cancel your order within 60 minutes of completion by visiting your account dashboard.",
        "Address Modifications: Address updates can be requested before the order status changes to 'Shipped'.",
        "Support Contact: For urgent changes after hours, email support@elitecart.com with your Order ID in the subject line."
      ]
    },
    {
      id: 'ret-1',
      category: 'returns',
      question: "What is your return policy?",
      points: [
        "30-Day Window: We offer hassle-free returns on all products within 30 days of the delivery date.",
        "Item Condition: Products must be unworn, unwashed, and in their original packaging with tags attached.",
        "Refund Method: Approved refunds are processed back to your original payment method within 5 to 7 business days.",
        "Exceptions: Clearance items marked 'Final Sale' are not eligible for returns or store credit."
      ]
    },
    {
      id: 'ret-2',
      category: 'returns',
      question: "How do I initiate a return or exchange?",
      points: [
        "Step 1: Log in and navigate to the 'My Orders' section under your Account profile.",
        "Step 2: Find the order containing the item you wish to return and click 'Request Return'.",
        "Step 3: Print the pre-paid return shipping label generated by our system.",
        "Step 4: Package the product securely, attach the label, and drop it off at any authorized carrier point."
      ]
    },
    {
      id: 'sec-1',
      category: 'security',
      question: "Is my personal and payment data secure?",
      points: [
        "Data Encryption: All data in transit is encrypted using 256-bit SSL/TLS protocols.",
        "Supabase Authentication: User profiles and logins are secured using Supabase's identity and JWT token standard.",
        "Stripe Compliance: Payment flows are fully PCI-DSS Level 1 compliant for premium transaction protection.",
        "No Data Selling: We do not sell, rent, or distribute user data to third-party marketing companies."
      ]
    },
    {
      id: 'sec-2',
      category: 'security',
      question: "How do I request deletion of my account?",
      points: [
        "Support Ticket: Open a deletion request by reaching out directly to privacy@elitecart.com.",
        "Data Erasure: Upon verification, we will remove all personal details, profiles, and active checkout cards.",
        "Regulatory Logs: In compliance with accounting and tax regulations, order invoices and transaction receipts are kept in archive.",
        "Timeline: Deletion is processed and completed within 3 business days of the request verification."
      ]
    }
  ]

  const toggleItem = (id: string) => {
    setExpandedItems(prev => ({
      ...prev,
      [id]: !prev[id]
    }))
  }

  // Filter FAQs based on active category and search input query
  const filteredFaqs = faqs.filter(faq => {
    const matchesCategory = activeCategory === 'all' || faq.category === activeCategory
    const matchesSearch = searchQuery === '' || 
      faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.points.some(p => p.toLowerCase().includes(searchQuery.toLowerCase()))
    return matchesCategory && matchesSearch
  })

  return (
    <div className="flex flex-col min-h-screen pb-16 bg-background">
      {/* Hero Header Banner */}
      <section className="relative overflow-hidden bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-violet-900/20 via-background to-background py-16 border-b border-muted/50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10 max-w-4xl text-center space-y-4">
          <Link
            href="/"
            className={cn(buttonVariants({ variant: "ghost", size: "sm" }), "inline-flex items-center gap-2 rounded-full border border-muted/30 hover:bg-muted/35 text-xs")}
          >
            <ArrowLeft size={12} /> Back to Shop
          </Link>
          <div className="pt-2">
            <Badge variant="outline" className="border-primary/30 text-primary bg-primary/5 px-3 py-1 font-semibold uppercase tracking-wider text-[10px]">
              Customer Support Center
            </Badge>
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight mt-2">
            Frequently Asked Questions
          </h1>
          <p className="text-muted-foreground text-sm max-w-lg mx-auto leading-relaxed">
            Need help? Check out our point-wise FAQ responses below. Use filters or search to quickly locate your answer.
          </p>

          {/* Search Bar Input */}
          <div className="max-w-md mx-auto relative mt-6">
            <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none text-muted-foreground">
              <Search size={16} />
            </div>
            <Input
              type="text"
              placeholder="Search FAQs (e.g. shipping, returns, stripe)..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 pr-4 py-2 w-full bg-muted/20 border-muted focus-visible:ring-primary rounded-full text-sm placeholder:text-muted-foreground/60 transition-all"
            />
          </div>
        </div>
      </section>

      {/* Main Content Area */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl mt-12 grid grid-cols-1 md:grid-cols-4 gap-8">
        
        {/* Left Sidebar Category Filter Buttons */}
        <div className="md:col-span-1 space-y-2 flex flex-row md:flex-col overflow-x-auto md:overflow-x-visible pb-4 md:pb-0 gap-2 md:gap-0 select-none no-scrollbar">
          {categories.map((cat) => {
            const Icon = cat.icon
            const isActive = activeCategory === cat.id
            return (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={cn(
                  "flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all border text-left w-full",
                  isActive
                    ? "bg-primary border-primary text-primary-foreground shadow-lg shadow-primary/20 scale-102"
                    : "bg-muted/10 border-muted/50 text-muted-foreground hover:bg-muted/30 hover:text-foreground"
                )}
              >
                <Icon size={14} className="flex-shrink-0" />
                {cat.label}
              </button>
            )
          })}
        </div>

        {/* Right FAQs Content */}
        <div className="md:col-span-3 space-y-4">
          {filteredFaqs.length === 0 ? (
            <div className="text-center p-12 border border-dashed border-muted rounded-2xl">
              <HelpCircle className="mx-auto text-muted-foreground mb-3" size={32} />
              <h3 className="font-bold text-sm text-foreground">No matches found</h3>
              <p className="text-xs text-muted-foreground mt-1 max-w-xs mx-auto">
                We couldn't find any FAQs matching your query: "{searchQuery}". Try updating your search tags.
              </p>
            </div>
          ) : (
            filteredFaqs.map((faq) => {
              const isExpanded = !!expandedItems[faq.id]
              return (
                <Card 
                  key={faq.id} 
                  className={cn(
                    "border-muted/50 bg-muted/5 shadow-sm overflow-hidden transition-all duration-300",
                    isExpanded ? "border-primary/20 bg-primary/2" : "hover:border-muted-foreground/30"
                  )}
                >
                  <CardHeader 
                    onClick={() => toggleItem(faq.id)}
                    className="p-4 flex flex-row items-center justify-between gap-4 cursor-pointer select-none"
                  >
                    <div className="flex items-center gap-3">
                      <div className={cn(
                        "p-1.5 rounded-lg transition-colors",
                        isExpanded ? "bg-primary/20 text-primary" : "bg-muted/30 text-muted-foreground"
                      )}>
                        <HelpCircle size={14} />
                      </div>
                      <span className="text-xs sm:text-sm font-bold text-foreground hover:text-primary transition-colors">
                        {faq.question}
                      </span>
                    </div>
                    <div>
                      {isExpanded ? (
                        <ChevronUp size={16} className="text-muted-foreground flex-shrink-0" />
                      ) : (
                        <ChevronDown size={16} className="text-muted-foreground flex-shrink-0" />
                      )}
                    </div>
                  </CardHeader>
                  
                  {isExpanded && (
                    <CardContent className="px-4 pb-5 pt-0 border-t border-muted/20 animate-fade-in">
                      <ul className="space-y-3 mt-4">
                        {faq.points.map((pt, pIdx) => {
                          const [label, detail] = pt.split(': ')
                          return (
                            <li key={pIdx} className="flex gap-2 items-start text-[11px] sm:text-xs">
                              <div className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 flex-shrink-0" />
                              <div className="space-y-0.5">
                                <strong className="text-foreground font-semibold">{label}:</strong>
                                <span className="text-muted-foreground block leading-relaxed">{detail}</span>
                              </div>
                            </li>
                          )
                        })}
                      </ul>
                    </CardContent>
                  )}
                </Card>
              )
            })
          )}

          {/* Direct Support Footer Card */}
          <div className="p-8 rounded-2xl bg-muted/20 border border-muted/50 text-center space-y-4 mt-8">
            <div className="mx-auto p-3 bg-primary/10 rounded-2xl w-fit text-primary">
              <Mail size={24} />
            </div>
            <h3 className="font-extrabold text-sm">Still have questions?</h3>
            <p className="text-xs text-muted-foreground max-w-sm mx-auto leading-relaxed">
              If your question isn't answered here, reach out to our customer care team anytime.
            </p>
            <div className="pt-2">
              <a 
                href="mailto:support@elitecart.com" 
                className={cn(buttonVariants({ size: "sm" }), "rounded-full font-bold px-6 text-xs shadow-lg shadow-primary/10")}
              >
                Email Customer Support
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
